// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from
// .\be\be_codegen.cpp:135

#ifndef _TAO_IDL_GIPSINETSKC_H_
#define _TAO_IDL_GIPSINETSKC_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include /**/ "gipsinetsk_common_export.h"
#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "tao/Object.h"
#include "tao/Objref_VarOut_T.h"
#include /**/ "tao/Versioned_Namespace.h"

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO GIPSINETSK_COMMON_Export

// TAO_IDL - Generated from 
// c:\ace_wrappers\tao\tao_idl\be\be_visitor_root/root_ch.cpp:62
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  class Collocation_Proxy_Broker;
  template<typename T> class Narrow_Utils;
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// .\be\be_interface.cpp:638

#if !defined (_CORBAGIPSINETSK__VAR_OUT_CH_)
#define _CORBAGIPSINETSK__VAR_OUT_CH_

class CORBAGIPSINETSK;
typedef CORBAGIPSINETSK *CORBAGIPSINETSK_ptr;

typedef
  TAO_Objref_Var_T<
      CORBAGIPSINETSK
    >
  CORBAGIPSINETSK_var;

typedef
  TAO_Objref_Out_T<
      CORBAGIPSINETSK
    >
  CORBAGIPSINETSK_out;

#endif /* end #if !defined */

// TAO_IDL - Generated from
// c:\ace_wrappers\tao\tao_idl\be\be_visitor_interface/interface_ch.cpp:54

#if !defined (_CORBAGIPSINETSK_CH_)
#define _CORBAGIPSINETSK_CH_

class GIPSINETSK_COMMON_Export CORBAGIPSINETSK
  : public virtual ::CORBA::Object
{
public:
  friend class TAO::Narrow_Utils<CORBAGIPSINETSK>;
  typedef CORBAGIPSINETSK_ptr _ptr_type;
  typedef CORBAGIPSINETSK_var _var_type;
  typedef CORBAGIPSINETSK_out _out_type;
  
  // The static operations.
  static CORBAGIPSINETSK_ptr _duplicate (CORBAGIPSINETSK_ptr obj);
  
  static void _tao_release (CORBAGIPSINETSK_ptr obj);
  
  static CORBAGIPSINETSK_ptr _narrow (::CORBA::Object_ptr obj);
  static CORBAGIPSINETSK_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
  static CORBAGIPSINETSK_ptr _nil (void)
  {
    return static_cast<CORBAGIPSINETSK_ptr> (0);
  }
  
  
  
  // TAO_IDL - Generated from
  // c:\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_ch.cpp:46
  
  virtual void getProjectXML (
      const char * filename,
      ::CORBA::String_out xmldata);
  
  // TAO_IDL - Generated from
  // c:\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_ch.cpp:46
  
  virtual void loadedProject (
      const char * filename);
  
  // TAO_IDL - Generated from
  // c:\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_ch.cpp:46
  
  virtual void startedService (
      const char * service,
      const char * nameservice);
  
  // TAO_IDL - Generated from
  // c:\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_ch.cpp:46
  
  virtual void setUICommand (
      const char * command);
  
  // TAO_IDL - Generated from
  // c:\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_ch.cpp:46
  
  virtual void closeConnection (
      const char * service);
  
  // TAO_IDL - Generated from
  // c:\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_ch.cpp:46
  
  virtual void testConnection (
      char *& data);
  
  // TAO_IDL - Generated from
  // c:\ace_wrappers\tao\tao_idl\be\be_visitor_interface/interface_ch.cpp:216
  
  virtual ::CORBA::Boolean _is_a (const char *type_id);
  virtual const char* _interface_repository_id (void) const;
  virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
private:
  TAO::Collocation_Proxy_Broker *the_TAO_CORBAGIPSINETSK_Proxy_Broker_;

protected:
  // Concrete interface only.
  CORBAGIPSINETSK (void);
  
  // These methods travese the inheritance tree and set the
  // parents piece of the given class in the right mode.
  virtual void CORBAGIPSINETSK_setup_collocation (void);
  
  // Concrete non-local interface only.
  CORBAGIPSINETSK (
      IOP::IOR *ior,
      TAO_ORB_Core *orb_core = 0);
  
  // Non-local interface only.
  CORBAGIPSINETSK (
      TAO_Stub *objref,
      ::CORBA::Boolean _tao_collocated = false,
      TAO_Abstract_ServantBase *servant = 0,
      TAO_ORB_Core *orb_core = 0);
  
  virtual ~CORBAGIPSINETSK (void);

private:
  // Private and unimplemented for concrete interfaces.
  CORBAGIPSINETSK (const CORBAGIPSINETSK &);
  
  void operator= (const CORBAGIPSINETSK &);
};

#endif /* end #if !defined */

// Proxy Broker Factory function pointer declarations.

// TAO_IDL - Generated from
// c:\ace_wrappers\tao\tao_idl\be\be_visitor_root/root.cpp:139

extern GIPSINETSK_COMMON_Export
TAO::Collocation_Proxy_Broker *
(*_TAO_CORBAGIPSINETSK_Proxy_Broker_Factory_function_pointer) (
    ::CORBA::Object_ptr obj
  );

// TAO_IDL - Generated from
// .\be\be_visitor_traits.cpp:64

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_CORBAGIPSINETSK__TRAITS_)
#define _CORBAGIPSINETSK__TRAITS_
  
  template<>
  struct GIPSINETSK_COMMON_Export Objref_Traits< ::CORBAGIPSINETSK>
  {
    static ::CORBAGIPSINETSK_ptr duplicate (
        ::CORBAGIPSINETSK_ptr
      );
    static void release (
        ::CORBAGIPSINETSK_ptr
      );
    static ::CORBAGIPSINETSK_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::CORBAGIPSINETSK_ptr p,
        TAO_OutputCDR & cdr
      );
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// c:\ace_wrappers\tao\tao_idl\be\be_visitor_interface/cdr_op_ch.cpp:55

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

GIPSINETSK_COMMON_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const CORBAGIPSINETSK_ptr );
GIPSINETSK_COMMON_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, CORBAGIPSINETSK_ptr &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// .\be\be_codegen.cpp:1219
#if defined (__ACE_INLINE__)
#include "GiPSiNetSKC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */


