// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from
// .\be\be_codegen.cpp:487

#ifndef _TAO_IDL_GIPSINETSKS_H_
#define _TAO_IDL_GIPSINETSKS_H_

#include /**/ "ace/pre.h"

#include "GiPSiNetSKC.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

#include "tao/Collocation_Proxy_Broker.h"
#include "tao/PortableServer/PortableServer.h"
#include "tao/PortableServer/Servant_Base.h"

// TAO_IDL - Generated from
// c:\ace_wrappers\tao\tao_idl\be\be_visitor_interface/interface_sh.cpp:87

class POA_CORBAGIPSINETSK;
typedef POA_CORBAGIPSINETSK *POA_CORBAGIPSINETSK_ptr;

class GIPSINETSK_COMMON_Export POA_CORBAGIPSINETSK
  : public virtual PortableServer::ServantBase
{
protected:
  POA_CORBAGIPSINETSK (void);

public:
  // Useful for template programming.
  typedef ::CORBAGIPSINETSK _stub_type;
  typedef ::CORBAGIPSINETSK_ptr _stub_ptr_type;
  typedef ::CORBAGIPSINETSK_var _stub_var_type;
  
  POA_CORBAGIPSINETSK (const POA_CORBAGIPSINETSK& rhs);
  virtual ~POA_CORBAGIPSINETSK (void);
  
  virtual ::CORBA::Boolean _is_a (const char* logical_type_id);
  
  static void _is_a_skel (
      TAO_ServerRequest & req,
      void * servant_upcall,
      void * servant
    );
  
  static void _non_existent_skel (
      TAO_ServerRequest & req,
      void * servant_upcall,
      void * servant
    );
  
  static void _interface_skel (
      TAO_ServerRequest & req,
      void * servant_upcall,
      void * servant
    );
  
  static void _component_skel (
      TAO_ServerRequest & req,
      void * servant_upcall,
      void * servant
    );
  
  static void _repository_id_skel (
      TAO_ServerRequest & req,
      void * servant_upcall,
      void * servant);
  
  virtual void _dispatch (
      TAO_ServerRequest & req,
      void * servant_upcall);
  
  ::CORBAGIPSINETSK *_this (void);
  
  virtual const char* _interface_repository_id (void) const;
  
  // TAO_IDL - Generated from
  // c:\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:45
  
  virtual void getProjectXML (
      const char * filename,
      ::CORBA::String_out xmldata) = 0;
  
  static void getProjectXML_skel (
      TAO_ServerRequest & server_request,
      void * servant_upcall,
      void * servant
    );
  
  // TAO_IDL - Generated from
  // c:\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:45
  
  virtual void loadedProject (
      const char * filename) = 0;
  
  static void loadedProject_skel (
      TAO_ServerRequest & server_request,
      void * servant_upcall,
      void * servant
    );
  
  // TAO_IDL - Generated from
  // c:\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:45
  
  virtual void startedService (
      const char * service,
      const char * nameservice) = 0;
  
  static void startedService_skel (
      TAO_ServerRequest & server_request,
      void * servant_upcall,
      void * servant
    );
  
  // TAO_IDL - Generated from
  // c:\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:45
  
  virtual void setUICommand (
      const char * command) = 0;
  
  static void setUICommand_skel (
      TAO_ServerRequest & server_request,
      void * servant_upcall,
      void * servant
    );
  
  // TAO_IDL - Generated from
  // c:\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:45
  
  virtual void closeConnection (
      const char * service) = 0;
  
  static void closeConnection_skel (
      TAO_ServerRequest & server_request,
      void * servant_upcall,
      void * servant
    );
  
  // TAO_IDL - Generated from
  // c:\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:45
  
  virtual void testConnection (
      char *& data) = 0;
  
  static void testConnection_skel (
      TAO_ServerRequest & server_request,
      void * servant_upcall,
      void * servant
    );
};

// TAO_IDL - Generated from 
// .\be\be_codegen.cpp:1281


#if defined (__ACE_INLINE__)
#include "GiPSiNetSKS.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"
#endif /* ifndef */

